/* Contenu par défaut des pages légales + FAQ — source unique partagée par
   legal.html, faq.html et admin.html. L'admin peut surcharger via site_content
   (clés « legal_<doc> » et « faq_fr / faq_en »). */
window.LEGAL_DEFAULTS = {
  legal: {
    fr: {
      mentions: { title:"Mentions légales", eff:"", body:`
        <p><b>Éditeur du site :</b> Le site bondipain.com est exploité par <b>BONDIPAIN SIGNATURE LTD</b>, société constituée à Maurice. BRN : C26236989. Siège social : Rue Colonel Draper, Beau-Bassin, Île Maurice.</p>
        <p><b>Responsable de publication :</b> BONDIPAIN SIGNATURE LTD (Jason Chris Noordine).</p>
        <p><b>Contact :</b> E-mail : info@bondipain.com | Téléphone : +230 5486 2333.</p>
        <p><b>Hébergeur et prestataire technique :</b> Vercel Inc., 340 S Lemon Ave #4133, Walnut, CA 91789, USA.</p>
        <p><b>Propriété intellectuelle :</b> Sauf indication contraire, le site, la marque, les textes, descriptions de menus, photographies, graphismes, logos et autres contenus appartiennent à BONDIPAIN SIGNATURE LTD ou sont utilisés sous licence. Ils ne peuvent être reproduits, adaptés, diffusés ou exploités commercialement sans autorisation écrite préalable, sauf dans les cas permis par la loi.</p>
        <p><b>Exactitude et disponibilité :</b> Bondipain prend des mesures raisonnables pour maintenir des informations exactes et un site disponible. Les menus, ingrédients, disponibilités, prix, zones de livraison et horaires peuvent évoluer. Les photographies sont illustratives ; la présentation peut varier sans modifier la nature essentielle du produit.</p>
        <p><b>Contact juridique ou confidentialité :</b> Écrire à info@bondipain.com avec l'objet « Juridique » ou « Confidentialité ».</p>` },
      cgv: { title:"Conditions générales de vente", eff:"Date d'effet : 1er août 2026", body:`
        <h3>1. Champ d'application et acceptation</h3><p>Les présentes CGV s'appliquent aux commandes passées sur bondipain.com, via un canal de commande approuvé ou par un compte entreprise. En commandant, le client confirme l'exactitude des informations fournies et accepte les présentes CGV. Les droits impératifs prévus par le droit mauricien demeurent applicables.</p>
        <h3>2. Capacité et comptes</h3><p>Le client doit avoir la capacité juridique de commander. Les identifiants doivent rester confidentiels. Le client est responsable des commandes passées via son compte, sauf usage non autorisé résultant d'un manquement de Bondipain à des mesures de sécurité raisonnables.</p>
        <h3>3. Produits et disponibilité</h3><p>Les repas sont préparés en quantités limitées et soumis à la disponibilité des ingrédients et de la production. Bondipain ne peut substituer un ingrédient non essentiel que si le caractère essentiel du plat n'est pas altéré et sans créer de risque allergène déclaré.</p>
        <h3>4. Commandes et formation du contrat</h3><p>Une commande constitue une offre d'achat. Le contrat n'est formé que lorsque Bondipain confirme son acceptation (e-mail, message, notification ou autre canal convenu). Bondipain peut refuser une commande pour indisponibilité, erreur de prix, échec de paiement, restriction de zone, suspicion de fraude ou motif opérationnel.</p>
        <h3>5. Heure limite de commande</h3><p>Les commandes doivent être passées avant 15 h 00 le jour ouvrable précédent. Les commandes tardives ne sont acceptées qu'à la discrétion de Bondipain et selon disponibilité.</p>
        <h3>6. Prix et taxes</h3><p>Les prix sont affichés en roupies mauriciennes et représentent le montant final à payer, TVA comprise le cas échéant. Bondipain peut modifier les prix avant l'acceptation d'une commande. Une commande confirmée n'est pas retarifée, sauf correction d'une erreur manifeste — le client peut alors annuler.</p>
        <h3>7. Paiement</h3><p>Les moyens acceptés sont ceux affichés au moment du paiement, actuellement Juice by MCB. Le paiement via MIPS s'appliquera après activation. Bondipain ne conserve pas les coordonnées complètes de carte lorsque le paiement est traité par un tiers.</p>
        <h3>8. Zone et délais de livraison</h3><p>La livraison est actuellement limitée aux adresses éligibles à Ébène affichées ou approuvées lors de la commande. Elle a généralement lieu du lundi au vendredi entre 11 h 00 et 14 h 00. Les horaires sont estimatifs.</p>
        <h3>9. Responsabilités du client</h3><p>Le client doit fournir une adresse correcte, un point de livraison accessible et un numéro joignable, et être disponible pour réceptionner la commande. En cas d'échec dû à des informations incorrectes, une inaccessibilité ou une absence, Bondipain peut considérer la commande comme livrée ou facturer des frais raisonnables de re-livraison, dans le respect de la loi.</p>
        <h3>10. Frais de livraison</h3><p>La livraison est gratuite dans la zone éligible actuelle, sauf frais différents clairement affichés avant validation.</p>
        <h3>11. Annulation par le client</h3><p>Une commande peut être annulée sans frais jusqu'à 15 h 00 le jour ouvrable précédant la livraison, en contactant Bondipain et en recevant une confirmation d'annulation. Passé ce délai, l'annulation et le remboursement ne sont généralement pas possibles, la préparation ayant pu débuter.</p>
        <h3>12. Annulation par Bondipain</h3><p>Bondipain peut annuler une commande pour indisponibilité, perturbation opérationnelle, sécurité, problème de paiement ou circonstances indépendantes de sa volonté. Tout montant payé sera remboursé via le moyen initial lorsque cela est raisonnablement possible.</p>
        <h3>13. Qualité, remboursements et avoirs</h3><p>Le client doit inspecter la commande rapidement. Tout article manquant, incorrect, endommagé, impropre ou substantiellement non conforme doit être signalé dès que possible, de préférence dans les 2 heures suivant la livraison, avec le numéro de commande et des photos si pertinent. Bondipain pourra remplacer l'article, rembourser le montant concerné, ou — uniquement avec l'accord du client — émettre un avoir.</p>
        <h3>14. Denrées périssables</h3><p>Les repas étant périssables et préparés pour une date précise, aucun remboursement n'est dû pour un simple changement d'avis après l'heure limite d'annulation, dans les limites de la loi.</p>
        <h3>15. Allergènes et informations alimentaires</h3><p>Les repas peuvent contenir ou entrer en contact avec des allergènes courants (céréales contenant du gluten, œufs, lait, arachides, fruits à coque, soja, sésame, moutarde, poisson, crustacés, etc.). Les clients allergiques ou ayant des exigences médicales doivent contacter Bondipain avant de commander. Malgré des précautions raisonnables, l'absence totale de contamination croisée ne peut être garantie. « Végétarien » ne signifie pas nécessairement végan ou sans allergène.</p>
        <h3>16. Manipulation après livraison</h3><p>Les repas doivent être consommés rapidement ou conservés et réchauffés selon les instructions fournies. Bondipain n'est pas responsable d'une détérioration due à un retard, une mauvaise conservation, une contamination ou un réchauffage après livraison, sauf responsabilité non exclue par la loi.</p>
        <h3>17. Commandes entreprise et employés</h3><p>Lorsqu'un employeur subventionne les repas ou gère un compte entreprise, les règles d'éligibilité, d'allocation, de contribution et de point de livraison peuvent être fixées par cet employeur. L'employé reste responsable de tout solde personnel affiché au paiement.</p>
        <h3>18. Promotions</h3><p>Les codes et offres promotionnels sont soumis à leur validité, éligibilité, montant minimum et disponibilité. Sauf mention expresse, les offres ne sont ni cumulables, ni échangeables contre espèces, ni applicables rétroactivement.</p>
        <h3>19. Utilisation du site</h3><p>Il est interdit de détourner le site, de tenter un accès non autorisé, de téléverser du code malveillant, d'extraire massivement du contenu, d'usurper une identité ou d'utiliser le service à des fins illégales ou frauduleuses.</p>
        <h3>20. Responsabilité</h3><p>Bondipain n'exclut pas les responsabilités qui ne peuvent légalement l'être (fraude, faute intentionnelle, décès ou dommage corporel dû à une négligence). Sous réserve des lois impératives, Bondipain n'est pas responsable des pertes indirectes, des pertes dues à des informations erronées fournies par le client, ou d'événements hors de son contrôle raisonnable.</p>
        <h3>21. Force majeure</h3><p>Bondipain n'est pas responsable d'un retard ou d'un manquement causé par des événements indépendants de sa volonté (intempéries, fermetures de routes, pannes réseau, mesures sanitaires, grèves, ruptures d'approvisionnement, décisions gouvernementales).</p>
        <h3>22. Modification des CGV</h3><p>Bondipain peut modifier les présentes CGV pour des raisons légales, opérationnelles ou de service. La version en vigueur lors de l'acceptation d'une commande s'applique à cette commande.</p>
        <h3>23. Droit applicable et litiges</h3><p>Les présentes CGV sont régies par le droit mauricien. Le client est invité à contacter d'abord Bondipain pour une solution amiable. Les tribunaux de Maurice sont compétents, sous réserve de tout for ou droit impératif de protection du consommateur.</p>
        <h3>24. Contact</h3><p>BONDIPAIN SIGNATURE LTD, Rue Colonel Draper, Beau-Bassin, Île Maurice — info@bondipain.com — +230 5486 2333.</p>` },
      confidentialite: { title:"Politique de confidentialité", eff:"Date d'effet : 1er août 2026", body:`
        <h3>1. Qui sommes-nous ?</h3><p>BONDIPAIN SIGNATURE LTD est responsable du traitement des données personnelles collectées via bondipain.com. Siège : Rue Colonel Draper, Beau-Bassin, Île Maurice. Contact confidentialité : info@bondipain.com.</p>
        <h3>2. Données collectées</h3><p>Identité et coordonnées ; identifiants de compte ; adresse et consignes de livraison ; affiliation entreprise et données d'allocation repas le cas échéant ; historique et préférences ; statut de paiement et références de transaction ; échanges avec le service client ; informations d'allergie ou de régime fournies volontairement ; données techniques (adresse IP, navigateur, appareil, cookies, journaux).</p>
        <h3>3. Données sensibles</h3><p>Les informations d'allergie et de santé peuvent être sensibles. Ne fournissez que les informations nécessaires à la sécurité de votre commande. Elles sont traitées uniquement lorsque la loi le permet, avec consentement explicite si requis, et l'accès est restreint.</p>
        <h3>4. Comment nous collectons</h3><p>Directement auprès des clients, auprès des employeurs gérant un programme repas, auprès des prestataires de paiement ou de livraison, et automatiquement via le site et les cookies.</p>
        <h3>5. Finalités et bases légales</h3><p>Création et gestion des comptes ; acceptation, préparation, paiement et livraison des commandes ; gestion des subventions entreprise ; messages de service ; réclamations et remboursements ; obligations comptables et légales ; protection du site et prévention de la fraude ; amélioration via analytics ; marketing uniquement lorsque permis. Selon l'activité : contrat, obligation légale, intérêt légitime, consentement ou autre base licite (Data Protection Act 2017).</p>
        <h3>6. Marketing</h3><p>Les communications promotionnelles (e-mail, SMS) ne sont envoyées que lorsque la loi le permet. Le consentement peut être retiré à tout moment via un lien de désinscription ou à info@bondipain.com. Les messages de service liés à une commande ne sont pas du marketing.</p>
        <h3>7. Cookies</h3><p>Les cookies nécessaires assurent sécurité, paiement, langue et session. Les cookies d'analyse ou publicitaires ne sont utilisés qu'avec l'information et le consentement requis. Voir notre <a href="#cookies">Politique cookies</a>.</p>
        <h3>8. Partage</h3><p>Nous pouvons partager des données limitées avec les livreurs, prestataires de paiement, hébergeur, prestataires de communication et support, conseils professionnels, employeurs (pour la gestion d'un programme repas) et autorités publiques lorsque la loi l'exige. Nous ne vendons pas de données personnelles.</p>
        <h3>9. Accès employeur</h3><p>Pour les programmes entreprise, l'employeur peut recevoir les informations nécessaires à la gestion de l'éligibilité, de l'allocation, de la contribution et de l'usage agrégé, sans détails inutiles sur les choix individuels ou la santé, sauf motif licite et clairement communiqué.</p>
        <h3>10. Transferts internationaux</h3><p>Certains prestataires peuvent traiter des données hors de Maurice. Bondipain applique les garanties requises par le droit mauricien.</p>
        <h3>11. Conservation</h3><p>Les données sont conservées le temps nécessaire aux finalités, obligations légales et fiscales, gestion des litiges et sécurité : paniers non finalisés jusqu'à 30 jours ; support jusqu'à 2 ans ; compte pendant sa durée de vie et jusqu'à 2 ans après clôture ; commandes, paiements et comptabilité pendant la durée légale.</p>
        <h3>12. Sécurité</h3><p>Bondipain applique des mesures organisationnelles et techniques raisonnables (contrôle d'accès, hébergement sécurisé, sauvegardes, confidentialité du personnel). Aucun système en ligne n'est totalement sûr.</p>
        <h3>13. Violations de données</h3><p>Lorsque la loi l'exige, Bondipain notifiera le Data Protection Office de Maurice et les personnes concernées dans les délais légaux.</p>
        <h3>14. Vos droits</h3><p>Sous réserve du Data Protection Act 2017 : accès, rectification, effacement, limitation, opposition, portabilité le cas échéant, retrait du consentement, et information sur les décisions automatisées. Demandes à info@bondipain.com (vérification d'identité possible).</p>
        <h3>15. Réclamations</h3><p>Vous pouvez contacter Bondipain, puis, le cas échéant, saisir le Data Protection Office de Maurice.</p>
        <h3>16. Enfants</h3><p>Le service n'est pas destiné à une commande autonome par des enfants. Un parent, tuteur ou adulte autorisé doit passer commande pour un mineur.</p>
        <h3>17. Liens tiers</h3><p>Le site peut renvoyer vers des sites tiers ou services de paiement, régis par leurs propres politiques.</p>
        <h3>18. Modifications</h3><p>Cette politique peut être mise à jour ; la date révisée sera affichée et les changements importants signalés.</p>
        <h3>19. Contact</h3><p>BONDIPAIN SIGNATURE LTD, Rue Colonel Draper, Beau-Bassin, Île Maurice — info@bondipain.com — +230 5486 2333.</p>` },
      cookies: { title:"Politique relative aux cookies", eff:"Date d'entrée en vigueur : 3 août 2026", body:`
        <p>Bondipain Signature Ltd (« Bondipain », « nous ») utilise des cookies et technologies similaires sur www.bondipain.com afin d'assurer le fonctionnement du site, la commande en ligne, la gestion des comptes, la mémorisation des préférences et l'amélioration de nos services.</p>
        <h3>1. Qu'est-ce qu'un cookie ?</h3><p>Un cookie est un petit fichier texte enregistré sur votre appareil lorsque vous consultez un site. Il aide le site à fonctionner, à mémoriser vos choix et à comprendre son utilisation.</p>
        <h3>2. Cookies que nous pouvons utiliser</h3>
        <ul>
          <li><b>Cookies strictement nécessaires</b> — sécurité, sessions de connexion, panier, paiement, traitement des commandes et mémorisation de vos choix de cookies.</li>
          <li><b>Cookies de préférence</b> — mémorisent la langue, le lieu de livraison, le créneau ou l'affichage.</li>
          <li><b>Cookies d'analyse</b> — comprennent les visites, la performance et le parcours de commande pour améliorer l'expérience.</li>
          <li><b>Cookies publicitaires / réseaux sociaux</b> — avec votre consentement, pour mesurer les campagnes ou afficher des contenus intégrés.</li>
          <li><b>Technologies de paiement et sécurité</b> — maintien d'une session de paiement sécurisée et prévention de la fraude.</li>
        </ul>
        <h3>3. Vos choix</h3><p>Les cookies strictement nécessaires sont utilisés automatiquement car le site ne peut fonctionner sans eux. Les cookies optionnels ne sont activés qu'après votre consentement. Vous pouvez modifier ou retirer votre consentement à tout moment, et supprimer ou bloquer les cookies via votre navigateur (au risque d'affecter la connexion, le panier ou le paiement).</p>
        <h3>4. Informations collectées</h3><p>Selon vos choix : appareil et navigateur, adresse IP, langue, pages visitées, statut de session, activité du panier et de commande, localisation approximative, interactions campagnes et données de performance.</p>
        <h3>5. Services tiers et transferts</h3><p>Certains cookies proviennent de tiers (hébergement, analyse, paiement, sécurité, cartographie, publicité, réseaux sociaux) pouvant traiter des informations hors de Maurice selon leurs propres politiques.</p>
        <h3>6. Conservation et mises à jour</h3><p>Certains cookies sont supprimés à la fermeture du navigateur, d'autres subsistent une durée limitée. Nous conservons les cookies le temps raisonnablement nécessaire et pouvons mettre à jour cette politique.</p>
        <h3>7. Nous contacter</h3><p>Bondipain Signature Ltd — info@bondipain.com — www.bondipain.com — Rue Colonel Draper, Beau-Bassin, Île Maurice.</p>` }
    },
    en: {
      mentions: { title:"Legal Notice", eff:"", body:`
        <p><b>Website operator:</b> bondipain.com is operated by <b>BONDIPAIN SIGNATURE LTD</b>, a company incorporated in Mauritius. BRN: C26236989. Registered office: Colonel Draper Street, Beau-Bassin, Mauritius.</p>
        <p><b>Publication manager:</b> BONDIPAIN SIGNATURE LTD (Jason Chris Noordine).</p>
        <p><b>Contact:</b> Email: info@bondipain.com | Telephone: +230 5486 2333.</p>
        <p><b>Hosting and technical provider:</b> Vercel Inc., 340 S Lemon Ave #4133, Walnut, CA 91789, USA.</p>
        <p><b>Intellectual property:</b> Unless otherwise stated, the website, brand, texts, menu descriptions, photographs, graphics, logos and other content are owned by or licensed to BONDIPAIN SIGNATURE LTD. They may not be reproduced, adapted, distributed or commercially used without prior written permission, except as permitted by law.</p>
        <p><b>Accuracy and availability:</b> Bondipain takes reasonable care to keep website information accurate and available. Menus, ingredients, availability, prices, delivery zones and operating hours may change. Photographs are illustrative; presentation may vary without changing the essential nature of the product.</p>
        <p><b>Contact for legal or privacy matters:</b> Write to info@bondipain.com with the subject "Legal" or "Privacy".</p>` },
      cgv: { title:"Terms and Conditions of Sale", eff:"Effective date: 1 August 2026", body:`
        <h3>1. Scope and acceptance</h3><p>These Terms apply to orders placed through bondipain.com, by an approved ordering channel, or through a corporate account. By placing an order, the customer confirms that the information supplied is accurate and accepts these Terms. Mandatory rights under Mauritian law remain unaffected.</p>
        <h3>2. Eligibility and accounts</h3><p>Customers must have legal capacity to place an order. Account credentials must be kept confidential. The customer is responsible for orders placed through the account unless unauthorised use results from Bondipain's failure to apply reasonable security.</p>
        <h3>3. Products and availability</h3><p>Meals are prepared in limited quantities and are subject to ingredient and production availability. Bondipain may substitute a non-essential ingredient only where the essential character of the dish is not altered and no declared allergen risk is created.</p>
        <h3>4. Orders and contract formation</h3><p>An order is an offer to purchase. A binding contract arises only when Bondipain confirms acceptance by email, message, website notification or other agreed channel. Bondipain may reject an order for unavailability, incorrect pricing, payment failure, delivery-zone restrictions, suspected fraud or operational reasons.</p>
        <h3>5. Order cut-off</h3><p>Orders should be placed by 15:00 on the preceding working day. Late orders are accepted only at Bondipain's discretion and subject to availability.</p>
        <h3>6. Prices and taxes</h3><p>Prices are shown in Mauritian rupees and represent the final payable consumer amount, inclusive of VAT where applicable. Bondipain may change prices before an order is accepted. A confirmed order will not be repriced except to correct an obvious error, in which case the customer may cancel.</p>
        <h3>7. Payment</h3><p>Accepted methods are those shown at checkout, currently Juice by MCB. Payment through MIPS will apply only after activation. Bondipain does not store full payment-card details where payment is processed by a third party.</p>
        <h3>8. Delivery area and timing</h3><p>Delivery is currently limited to eligible locations in Ébène displayed or approved at checkout. Delivery generally occurs Monday to Friday between 11:00 and 14:00. Times are estimates.</p>
        <h3>9. Customer delivery responsibilities</h3><p>The customer must provide a correct address, accessible delivery point and reachable phone number, and be available to receive the order. If delivery cannot be completed because of incorrect details, inaccessibility or absence, Bondipain may treat the order as delivered or charge reasonable redelivery costs, subject to applicable law.</p>
        <h3>10. Delivery charges</h3><p>Delivery is free within the currently eligible zone unless a different charge is clearly displayed before checkout.</p>
        <h3>11. Cancellation by the customer</h3><p>An order may be cancelled without charge until 15:00 on the working day preceding delivery by contacting Bondipain and receiving cancellation confirmation. After that deadline, cancellation and refund are generally unavailable because procurement or preparation may have begun.</p>
        <h3>12. Cancellation by Bondipain</h3><p>Bondipain may cancel an order because of unavailable ingredients, operational disruption, safety concerns, payment problems or circumstances beyond reasonable control. Any amount paid will be refunded through the original method where reasonably possible.</p>
        <h3>13. Quality issues, refunds and credits</h3><p>Customers should inspect the order promptly. Missing, incorrect, damaged, unsafe or materially non-compliant items must be reported as soon as possible, preferably within 2 hours of delivery, with the order number and supporting photographs where appropriate. Bondipain may replace the item, refund the affected amount, or—only with the customer's agreement—issue a credit.</p>
        <h3>14. Perishable food and change of mind</h3><p>Because meals are perishable and prepared for a specific delivery date, there is no refund for a simple change of mind after the cancellation deadline, to the extent permitted by law.</p>
        <h3>15. Allergens and dietary information</h3><p>Meals may contain or come into contact with common allergens, including cereals containing gluten, eggs, milk, peanuts, tree nuts, soy, sesame, mustard, fish, crustaceans and others. Customers with allergies must contact Bondipain before ordering. An allergen-free environment and complete prevention of cross-contact cannot be guaranteed. "Vegetarian" does not necessarily mean vegan or allergen-free.</p>
        <h3>16. Food handling after delivery</h3><p>Meals should be consumed promptly or stored and reheated per any instructions supplied. Bondipain is not responsible for deterioration caused by delay, incorrect storage, contamination or reheating after delivery, except where liability cannot lawfully be excluded.</p>
        <h3>17. Corporate and employee orders</h3><p>Where an employer subsidises meals or operates a corporate account, eligibility, allowance, contribution and delivery-point rules may be set by that employer. The employee remains responsible for any personal balance shown at checkout.</p>
        <h3>18. Promotions</h3><p>Promotional codes and offers are subject to their stated validity, eligibility, minimum spend and availability. Unless expressly permitted, offers cannot be combined, exchanged for cash or applied retrospectively.</p>
        <h3>19. Website use</h3><p>Users must not misuse the website, attempt unauthorised access, upload malicious code, scrape content at scale, impersonate another person, or use the service for unlawful or fraudulent purposes.</p>
        <h3>20. Liability</h3><p>Bondipain does not exclude liability that cannot lawfully be excluded, including fraud, wilful misconduct, or death or personal injury caused by negligence. Subject to mandatory law, Bondipain is not liable for indirect or consequential losses, loss caused by customer-provided incorrect information, or events outside reasonable control.</p>
        <h3>21. Force majeure</h3><p>Bondipain is not responsible for delay or failure caused by events beyond reasonable control, including severe weather, road closures, utility or network failures, public-health measures, strikes, supply disruption or governmental action.</p>
        <h3>22. Changes to these Terms</h3><p>Bondipain may amend these Terms for legal, operational or service reasons. The version in force when an order is accepted applies to that order.</p>
        <h3>23. Governing law and disputes</h3><p>These Terms are governed by the laws of Mauritius. Customers should first contact Bondipain to seek an amicable solution. The courts of Mauritius have jurisdiction, subject to any mandatory consumer-protection forum or right.</p>
        <h3>24. Contact</h3><p>BONDIPAIN SIGNATURE LTD, Colonel Draper Street, Beau-Bassin, Mauritius — info@bondipain.com — +230 5486 2333.</p>` },
      confidentialite: { title:"Privacy Policy", eff:"Effective date: 1 August 2026", body:`
        <h3>1. Who we are</h3><p>BONDIPAIN SIGNATURE LTD is the controller of personal data processed through bondipain.com. Registered office: Colonel Draper Street, Beau-Bassin, Mauritius. Privacy contact: info@bondipain.com.</p>
        <h3>2. Data we collect</h3><p>Identity and contact details; account credentials; delivery address and instructions; employer/corporate affiliation and meal-allowance information where applicable; order history and preferences; payment status and transaction references; customer-service communications; allergy or dietary information voluntarily supplied; and technical data such as IP address, browser, device, cookies and usage logs.</p>
        <h3>3. Special-category or sensitive information</h3><p>Allergy and health-related dietary information may be sensitive. Provide only information necessary for order safety. We process it only where permitted by law, including with explicit consent where required, and restrict access to personnel who need it.</p>
        <h3>4. How we collect data</h3><p>Directly from customers, from employers administering corporate meal programmes, from payment or delivery providers, and automatically through the website and cookies.</p>
        <h3>5. Purposes and lawful grounds</h3><p>To create and manage accounts; accept, prepare, pay for and deliver orders; administer corporate subsidies; communicate service messages; handle complaints and refunds; keep accounting and legal records; protect the website and prevent fraud; improve services through analytics; and send marketing only where permitted. Processing is based on contract, legal obligation, legitimate interests, consent, or another lawful ground under the Data Protection Act 2017.</p>
        <h3>6. Marketing</h3><p>Promotional email, SMS or similar marketing is sent only where legally permitted. Consent can be withdrawn at any time through an unsubscribe option or by contacting info@bondipain.com. Service messages about an order are not marketing.</p>
        <h3>7. Cookies</h3><p>Necessary cookies support security, checkout, language and session functions. Analytics or advertising cookies are used only with required notice and consent. See our <a href="#cookies">Cookie Policy</a>.</p>
        <h3>8. Sharing</h3><p>We may share limited data with delivery personnel, payment processors, hosting and website providers, communications and support providers, professional advisers, corporate employers where needed, and public authorities where legally required. We do not sell personal data.</p>
        <h3>9. Employer access</h3><p>For corporate programmes, an employer may receive information needed to administer eligibility, allowance, contribution and aggregated usage, without unnecessary details about individual food choices or health information unless lawful and clearly disclosed.</p>
        <h3>10. International transfers</h3><p>Some service providers may process data outside Mauritius. Bondipain uses appropriate safeguards required by Mauritian data-protection law.</p>
        <h3>11. Retention</h3><p>Personal data is retained only as long as needed: unsuccessful checkout data up to 30 days; customer-support records up to 2 years; account data while active and up to 2 years after closure; order, payment and accounting records for the legally required period.</p>
        <h3>12. Security</h3><p>Bondipain applies reasonable organisational and technical measures, including access control, secure hosting, backups, staff confidentiality and third-party due diligence. No online system can be guaranteed completely secure.</p>
        <h3>13. Data breaches</h3><p>Where required by law, Bondipain will notify the Mauritius Data Protection Office and affected individuals within the applicable legal timeframe.</p>
        <h3>14. Your rights</h3><p>Subject to the Data Protection Act 2017, individuals may request access, correction, erasure, restriction, objection, data portability where applicable, withdrawal of consent, and information about automated decision-making. Requests to info@bondipain.com.</p>
        <h3>15. Complaints</h3><p>Individuals may first contact Bondipain and also have the right to complain to the Mauritius Data Protection Office.</p>
        <h3>16. Children</h3><p>The service is not intended for children to order independently. A parent, guardian or authorised adult should place an order for a minor.</p>
        <h3>17. Third-party links</h3><p>The website may link to third-party sites or payment services, governed by their own notices.</p>
        <h3>18. Changes</h3><p>This Policy may be updated to reflect legal, technical or operational changes. The revised date will be displayed.</p>
        <h3>19. Contact</h3><p>BONDIPAIN SIGNATURE LTD, Colonel Draper Street, Beau-Bassin, Mauritius — info@bondipain.com — +230 5486 2333.</p>` },
      cookies: { title:"Cookie Policy", eff:"Effective date: 3 August 2026", body:`
        <p>Bondipain Signature Ltd ("Bondipain", "we") uses cookies and similar technologies on www.bondipain.com to operate the website, support online food ordering, manage accounts, remember preferences and improve our services.</p>
        <h3>1. What are cookies?</h3><p>Cookies are small text files stored on your device when you visit a website. They help the website function, remember your choices and understand how it is used.</p>
        <h3>2. Cookies we may use</h3>
        <ul>
          <li><b>Strictly necessary cookies</b> — website security, login sessions, baskets, checkout, order processing and recording your cookie choices.</li>
          <li><b>Preference cookies</b> — remember language, delivery location, selected time slot or display preferences.</li>
          <li><b>Analytics cookies</b> — understand visits, performance and the ordering journey to improve the experience.</li>
          <li><b>Advertising and social media cookies</b> — with your consent, measure campaigns or enable embedded content.</li>
          <li><b>Payment and security technologies</b> — maintain a secure payment session, confirm transactions and prevent fraud.</li>
        </ul>
        <h3>3. Your choices</h3><p>Strictly necessary cookies are used automatically because the website cannot work properly without them. Optional cookies are activated only after you give consent. You can change or withdraw consent at any time and delete or block cookies through your browser, although this may affect login, basket or checkout functions.</p>
        <h3>4. Information collected</h3><p>Depending on your choices: device and browser information, IP address, language preference, pages visited, session status, basket and order-flow activity, approximate location, campaign interactions and technical performance data.</p>
        <h3>5. Third-party services and transfers</h3><p>Some cookies may be provided by third parties (hosting, analytics, payment, security, mapping, advertising or social media), which may process information outside Mauritius under their own privacy policies.</p>
        <h3>6. Retention and updates</h3><p>Some cookies are deleted when you close your browser; others remain for a limited period. We retain cookies only as long as reasonably necessary and may update this policy.</p>
        <h3>7. Contact us</h3><p>Bondipain Signature Ltd — info@bondipain.com — www.bondipain.com — Colonel Draper Street, Beau-Bassin, Mauritius.</p>` }
    }
  },
  faq: {
    fr: [
      ["Quelle est la zone de livraison de Bondipain ?","Bondipain livre uniquement à <b>Ébène</b> (Île Maurice), aux adresses et points de livraison éligibles affichés au moment de la commande."],
      ["Quels sont les horaires de livraison ?","Du <b>lundi au vendredi</b>, généralement entre <b>11 h 00 et 14 h 00</b>, hors jours fériés ou fermetures exceptionnelles. Les horaires sont estimatifs."],
      ["Jusqu'à quand puis-je commander ?","Commandez <b>avant 15 h 00 le jour ouvrable précédent</b>. Toute commande après l'heure limite reste soumise à acceptation et disponibilité."],
      ["Quels moyens de paiement acceptez-vous ?","Actuellement <b>Juice by MCB</b>. Le paiement via MIPS sera ajouté après activation et tests. Les espèces à la livraison peuvent aussi être proposées."],
      ["La livraison est-elle payante ?","La livraison est <b>gratuite</b> dans la zone éligible actuelle (Ébène), sauf si des frais différents sont clairement affichés avant validation."],
      ["Puis-je annuler ou être remboursé ?","Annulation gratuite jusqu'à <b>15 h 00 le jour ouvrable précédant la livraison</b>. Après ce délai, aucune annulation ni remboursement (les repas pouvant déjà être préparés), sauf annulation par Bondipain, absence de livraison ou repas défectueux. Le remboursement s'effectue via le moyen de paiement initial."],
      ["Comment signaler un problème sur ma commande ?","Contactez <b>info@bondipain.com</b> ou le <b>+230 5486 2333</b> dès que possible, de préférence dans les 2 heures suivant la livraison, avec votre numéro de commande, les détails et des photos si pertinent."],
      ["Gérez-vous les allergènes ?","Les clients allergiques doivent <b>contacter Bondipain avant de commander</b>. Le risque de contamination croisée ne peut être totalement exclu dans une cuisine partagée. « Végétarien » ne signifie pas nécessairement sans allergène."],
      ["Comment sont affichés les prix ?","Les prix sont affichés en <b>roupies mauriciennes (Rs)</b>, prix final consommateur, incluant tous les frais obligatoires."],
      ["Proposez-vous un avantage repas pour les entreprises ?","Oui. Les entreprises peuvent subventionner les repas de leurs employés via un <b>compte entreprise</b> : l'employé ne paie que son solde au moment de la commande. Voir la page <a href='entreprises.html'>Entreprises</a>."]
    ],
    en: [
      ["What is Bondipain's delivery area?","Bondipain delivers to <b>Ébène</b> (Mauritius) only, at the eligible addresses and delivery points shown at checkout."],
      ["What are the delivery hours?","<b>Monday to Friday</b>, generally between <b>11:00 and 14:00</b>, excluding public holidays or exceptional closures. Delivery times are estimates."],
      ["Until when can I order?","Order <b>by 15:00 on the preceding working day</b>. Orders after the cut-off are subject to acceptance and availability."],
      ["Which payment methods do you accept?","Currently <b>Juice by MCB</b>. Payment through MIPS will be added once activated and tested. Cash on delivery may also be offered."],
      ["Is delivery free?","Delivery is <b>free</b> within the current eligible zone (Ébène), unless a different fee is clearly shown before checkout."],
      ["Can I cancel or get a refund?","Free cancellation until <b>15:00 on the working day before delivery</b>. After that, no cancellation or refund (meals may already be prepared), except where Bondipain cancels, fails to deliver, or the meal is materially defective. Refunds use the original payment method."],
      ["How do I report an issue with my order?","Contact <b>info@bondipain.com</b> or <b>+230 5486 2333</b> as soon as possible, preferably within 2 hours of delivery, with your order number, details and photographs where relevant."],
      ["Do you handle allergens?","Customers with allergies must <b>contact Bondipain before ordering</b>. Cross-contact cannot be completely excluded in a shared kitchen. \"Vegetarian\" does not necessarily mean allergen-free."],
      ["How are prices displayed?","Prices are shown in <b>Mauritian rupees (Rs)</b>, as the final consumer price, inclusive of all mandatory charges."],
      ["Do you offer a company meal benefit?","Yes. Companies can subsidise their employees' meals through a <b>corporate account</b>: the employee pays only their balance at checkout. See the <a href='entreprises.html'>Companies</a> page."]
    ]
  }
};
